updating test if file readable

diff --git a/hw1 b/hw1
--- a/hw1
+++ b/hw1
@@ -17,24 +17,41 @@ then
   exit 1
 fi
 
+# check that file exists and is readable
+if [[ -a $2 && -r $2 ]]
+then
+  echo "file found"
+else
+  echo "./stats: cannot read $2" 1>&2
+  exit 1
+fi
+
+
+
 # check to see if text file is there. If not, let user enter into temp file
 if [[ "$#" -eq 2 ]]
 then
   # if argument is there, use it as the input
   input=$2
 else
-  echo "cat needs to be here"
-  exit 0
+  # prompt user with cat for stdin
+  echo "enter vals"
+  cat > "$tempfile"
+  input="$tempfile"
+
 fi
 
 
+# check for existing but empty file --- TO DO!!!!!!
 
-#echo $input
+
+# check for cannot read file
 
 
-# check for existing but empty file
 
 # Do if/else check, this is for rows. -----------------
+# check for -r -c and -both (-both should show usage )
+
 while read line
 do
   #echo $line
